### ISSUE TITLE
How do I get the highest resolution?

### ISSUE THREAD

**Issue by jsdryan** [locoloader/chrome-extension#1]
As mentioned in the main topic, the resolution of some videos is 1080P or 2160P, but the maximum resolution of the video captured by this tool is only 720P (1280 x 720), I am already a paid member, is there any way to fix or improve this problem?

**Comment by locoloader** [comment]
This question is not related to the Chrome Extension. Please contact info@locoloader.com.

**Comment by savageroy571-stack** [comment]
> As mentioned in the main topic, the resolution of some videos is 1080P or 2160P, but the maximum resolution of the video captured by this tool is only 720P (1280 x 720), I am already a paid member, is there any way to fix or improve this problem?
